# NumPy - Fundamentals

* NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy dimensions are called axes. The number of axes is rank.

* eg1: The coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. That axis has a length of 3. 
* eg2: [[ 1., 0., 0.],
       [ 0., 1., 2.]] 
     The array has rank 2 (it is 2-dimensional). The first dimension (axis) has a length of 2, the second dimension has a length of 3.

* How to create a NumPy Array ?

In [2]:
import numpy as np

##### One dimentional array

In [3]:
lst1 = [1,2,3,4] # convert a list to numpy array
np_arr1 = np.array(lst1)
print("One dimensional Array np_arr1 : ",np_arr1)
print("Shape of the Array : ", np_arr1.shape)

One dimensional Array np_arr1 :  [1 2 3 4]
Shape of the Array :  (4,)


##### Two dimentional array

In [18]:
lst2 = [5,6,7,8]
lst_of_lsts = [lst1, lst2]
np_arr2 = np.array(lst_of_lsts)
print("Two dimensional Array np_arr2 : ")
print(np_arr2)
print("Shape of the Array : ", np_arr2.shape)

Two dimensional Array np_arr2 : 
[[1 2 3 4]
 [5 6 7 8]]
Shape of the Array :  (2, 4)


In [19]:
np_arr2.dtype

dtype('int32')

In [20]:
np_arr2.ndim # array dimensions, 2 dimensioinal array

2

In [21]:
np_arr2.size

8

* The class of NumPy’s array ndarray. It is also known by the alias array. 

In [22]:
type(np_arr2)

numpy.ndarray

* **np.arange()** This method is similar to range() in Python but returns ndarray. This take Start, Stop, Step and dtype parameters. This method accepts float values also.
* **np.reshape()** Will reshape the array to given dimensions

In [24]:
np_arr3 = np.arange(start=2, stop=32,step=2, dtype='int64')
print("np_arr3 : ", np_arr3)
print("type of np_arr3 : ", type(np_arr3))

np_arr3 :  [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
type of np_arr3 :  <class 'numpy.ndarray'>


In [28]:
np_arr4 = np_arr3.reshape(3,-1)
print("Reshaped Array : ")
print(np_arr4)

Reshaped Array : 
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]]


* **zeros()** The function zeros creates an array full of zeros.
* **ones()** The function ones creates an array full of ones.
* **empty()** The function empty creates an array whose initial content is random and depends on the state of the memory. By default, the dtype of the created array is float64.

In [29]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
np.ones( (2,3,4), dtype=np.int16 )                # 3-dimensional array, dtype can also be specified

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [32]:
np.empty( (2,3) )

array([[0., 0., 0.],
       [0., 0., 0.]])

* **eye()** The function eye() generates identity matrix

In [33]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
A = np.arange(9).reshape((3,3))
print(A)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [35]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [36]:
np.dot(A, I)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [37]:
np.dot(I, A)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

* **linspace()** This method return evenly spaced numbers over a specified interval.

In [ ]:
np.linspace(2.0, 3.0, num=10)

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

In [ ]:
np.linspace(2.0, 3.0, num=10, retstep=True)

# Basic Operations

In [ ]:
a = np.array([10, 20, 30, 40])
print("Array a : ", a)
b = np.arange(4)
print("Array b : ", b)
c = a - b
print("Array c = a - b : ", c)

In [ ]:
a*b

In [ ]:
b/a

In [ ]:
print("Brodcasting - Scalar 10 multiplied with Array a : ", 10*a)

In [ ]:
print("Square of a Matrix b : ", b**2)

In [ ]:
a<35

* Some operations, such as **+=** and ***=**, act in place to modify an existing array rather than create a new one.

In [ ]:
a *= 3  # same as a = a*3
print(a)

In [ ]:
b += a # same as b = b +a
print(b)

#####  dot() The matrix product can be performed using the dot function.

In [38]:
A = np.array( [[1,1],
                [0,1]] )
print(A)
B = np.array( [[2,0],
                 [3,4]] )
print(B)

[[1 1]
 [0 1]]
[[2 0]
 [3 4]]


In [39]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [40]:
np.dot(A,B)

array([[5, 4],
       [3, 4]])

* **Aggregate Functions** such as sum, min, max, cumsum are implemented as methods of ndarray class. 
* Specifying the axis parameter you can apply an operation along the specified **axis(0 - cloumn, 1 - row)**  of an array 

In [41]:
agg_arr = np.arange(12).reshape(3,4)
print(agg_arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [42]:
agg_arr.sum()

66

In [46]:
agg_arr.sum(axis=0, keepdims=False)

array([12, 15, 18, 21])

In [44]:
agg_arr.sum(axis=1)

array([ 6, 22, 38])

In [47]:
agg_arr.cumsum(axis=1)  

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

* **Universal Functions** NumPy provides familiar mathematical functions such as sin, cos, and exp.

In [48]:
C = np.arange(3)
np.exp(C)

array([1.        , 2.71828183, 7.3890561 ])

In [49]:
np.sqrt(C)

array([0.        , 1.        , 1.41421356])

In [50]:
np.sin(C)

array([0.        , 0.84147098, 0.90929743])

In [51]:
D = np.array([2., -1., 4.])
np.add(C, D)

array([2., 0., 6.])

####  Indexing & Slicing

* One-dimensional arrays can be indexed, sliced and iterated over, much like lists 

In [52]:
slice_arr = np.arange(10)**3
print("Slice Array : ", slice_arr)

Slice Array :  [  0   1   8  27  64 125 216 343 512 729]


In [53]:
slice_arr[2]

8

In [54]:
slice_arr[2:5]

array([ 8, 27, 64], dtype=int32)

In [57]:
slice_arr[4:]

array([ 64, 125, 216, 343, 512, 729], dtype=int32)

In [58]:
slice_arr[2: : 2]

array([  8,  64, 216, 512], dtype=int32)

In [59]:
slice_arr[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [60]:
slice_arr[-1]

729

* Indexing and Slicing on Two-dimensional arrays

In [61]:
arr2d = np.arange(25).reshape((5,5))

In [62]:
print(arr2d)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [63]:
print(arr2d[2])

[10 11 12 13 14]


In [72]:
print(arr2d[[2,3], :])

[[10 11 12 13 14]
 [15 16 17 18 19]]


In [73]:
arr2d[:, [2,4]]  #Fancy indexing allows the following

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24]])

In [74]:
arr2d[[4,0,2]]   #Allows in any order

array([[20, 21, 22, 23, 24],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

##### Looping

In [75]:
for x in arr2d:
    print(x)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [76]:
for row in arr2d:
    for i in row:
        print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


# Shape Manipulation

In [77]:
shape_mnpl = np.arange(20).reshape((5,4))
print(shape_mnpl)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [78]:
shape_mnpl.ravel() # ravel() method makes the arry to one dimentional

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [79]:
shape_mnpl.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [80]:
shape_mnpl.T # Transpose of a matrix

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [81]:
shape_mnpl.reshape(-1, 5) # If a dimension is given as -1 in a reshaping operation, 
                  #the other dimensions are automatically calculated

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
shape_mnpl.resize(10,2)        #The reshape function returns its argument with a modified shape, 
                        #whereas the ndarray.resize method modifies the array itself
print(shape_mnpl)   

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


##### Stacking together different arrays

In [96]:
k = np.array([[8,8],[20, 15]])
print(k)
l = np.array([[2,4], [3,9]])
print(l)

[[ 8  8]
 [20 15]]
[[2 4]
 [3 9]]


In [97]:
np.vstack( (k, l) )

array([[ 8,  8],
       [20, 15],
       [ 2,  4],
       [ 3,  9]])

In [98]:
np.hstack( (k,l) )

array([[ 8,  8,  2,  4],
       [20, 15,  3,  9]])

In [99]:
np.r_['r',[1,2,3], [4,5,6]]

matrix([[1, 2, 3, 4, 5, 6]])

In [100]:
np.r_['c',[1,2,3], [4,5,6]]

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [101]:
np.c_[np.array([[1,2,3]]), np.array([[4,5,6]])]

array([[1, 2, 3, 4, 5, 6]])

In [102]:
countries = np.array(['France', 'Germany', 'USA', 'Russia','USA','Mexico','Germany'])

np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'], dtype='<U7')

In [103]:
np.in1d(['France','USA','Sweden'],countries)

array([ True,  True, False])